# Generated by Django 4.2.5 on 2023-09-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoModel',
            new_name='Photo',
        ),
    ]
